### ISSUE TITLE
Vietnamese check

### ISSUE THREAD

**Issue by alexeiva** [alexeiva/badscript#1]
@crystaltype could you please have a look at the Vietnamese?

<img width="1065" alt="screen shot 2016-08-03 at 00 29 46" src="https://cloud.githubusercontent.com/assets/16634089/17357463/813bf3fc-5911-11e6-8a14-3430b226cfe9.png">
<img width="1086" alt="screen shot 2016-08-03 at 00 30 01" src="https://cloud.githubusercontent.com/assets/16634089/17357464/81501dbe-5911-11e6-9703-703e6725bb8b.png">
<img width="1054" alt="screen shot 2016-08-03 at 00 29 08" src="https://cloud.githubusercontent.com/assets/16634089/17357468/8483b658-5911-11e6-88aa-ad7831609147.png">

**Comment by crystaltype** [comment]
Excellent job!
Although I think the circumflex in Ô should be moved to the right a little
bit.
Well done 😁Alexei!
